services:
  - type: web
    name: friendly-medbot-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Optional custom port

  - type: static
    name: friendly-medbot-frontend
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/dist
    autoDeploy: true
